version: '3'
services:
  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jwt-auth-tuto
    volumes:
      - ./data:/var/lib/postgresql/data
    expose:
      - '5432'
  adminer:
    container_name: adminer-container
    image: adminer
    restart: always
    ports:
      - '8080:8080'
  api:
    container_name: api
    build: ./server
    ports:
      - '4000:4000'
    expose:
      - '4000'
    links:
      - postgres
    environment:
      - DATABASE_HOST=postgres
    command: npm run dev
  web:
    container_name: web
    build: ./web
    ports:
      - '3000:3000'
    links:
      - api
    environment:
      - REACT_APP_APOLLO_CLIENT=http://localhost:4000/graphql
      - REACT_APP_REFRESH_TOKEN=http://localhost:4000/refresh-token
    command: npm run start
