version: '2'
services:
  postgres:
    container_name: postgres-container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jwt-auth-tuto
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  adminer:
    container_name: adminer-container
    image: adminer
    restart: always
    ports:
      - '8080:8080'
